services:
  app:
    image: ghcr.io/almonium-platform/almonium-be:${TAG}
    container_name: app_${DEPLOY_SLOT}
    environment:
      TAG: ${TAG}
      DEPLOY_SLOT: ${DEPLOY_SLOT}
      SERVER_PORT: ${APP_INTERNAL_PORT}

      # Server Configuration
      LOCAL_PORT: ${LOCAL_PORT}
      DEBUG_PORT: ${DEBUG_PORT}
      SPRING_PROFILE: ${SPRING_PROFILE}

      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET}

      # Database Configuration
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      # API Keys
      RAPID_API_KEY: ${RAPID_API_KEY}
      WORDNIK_KEY: ${WORDNIK_KEY}
      YANDEX_KEY: ${YANDEX_KEY}
      OPENAI_KEY: ${OPENAI_KEY}

      # Stripe Configuration
      STRIPE_KEY: ${STRIPE_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}

      # Stream Configuration
      STREAM_KEY: ${STREAM_KEY}
      STREAM_SECRET: ${STREAM_SECRET}

      # Google Cloud Configuration
      GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID}
      GOOGLE_SERVICE_ACCOUNT_KEY_BASE64: ${GOOGLE_SERVICE_ACCOUNT_KEY_BASE64} # Your app decodes this

      # Firebase Configuration
      FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}

      # OAuth2 Configuration
      GOOGLE_ID: ${GOOGLE_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      FACEBOOK_ID: ${FACEBOOK_ID}
      FACEBOOK_SECRET: ${FACEBOOK_SECRET}
      APPLE_ID: ${APPLE_ID}
      APPLE_SECRET: ${APPLE_SECRET}

      # RabbitMQ Configuration
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}

      # Mail Configuration
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

    networks:
      - broker-net
    ports:
      - "${HOST_PORT}:${APP_INTERNAL_PORT}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${APP_INTERNAL_PORT}/api/v1/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped

networks:
  broker-net:
    external: true
