services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby_server
    networks:
      - proxy-net
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Etc/UTC
    volumes:
      - /var/lib/emby:/config
      - /home/almonium/media:/media
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.emby-router.rule=Host(`emby.almonium.com`)"
      - "traefik.http.routers.emby-router.entrypoints=websecure"
      - "traefik.http.routers.emby-router.tls.certresolver=porkbun"
      - "traefik.http.services.emby-svc.loadbalancer.server.port=8096"

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing_server
    networks:
      - proxy-net
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Etc/UTC
    volumes:
      - /home/almonium/syncthing/config:/config
      - /home/almonium/media:/media
    ports:
      - "8384:8384"
      - "22000:22000/tcp"
      - "21027:21027/udp"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing-router.rule=Host(`syncthing.almonium.com`)"
      - "traefik.http.routers.syncthing-router.entrypoints=websecure"
      - "traefik.http.routers.syncthing-router.tls.certresolver=porkbun"
      - "traefik.http.services.syncthing-svc.loadbalancer.server.port=8384"

networks:
  proxy-net:
    external: true
