services:
  traefik:
    image: traefik:v3.4.1
    container_name: traefik_proxy
    command:
      - "--api.insecure=true" # for Traefik dashboard
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.porkbun.acme.email=tech@almonium.com"
      - "--certificatesresolvers.porkbun.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.porkbun.acme.dnschallenge.provider=porkbun"
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080" # Traefik dashboard
    environment:
      - PORKBUN_API_KEY=${SHELL_PORKBUN_API_KEY}
      - PORKBUN_SECRET_API_KEY=${SHELL_PORKBUN_SECRET_KEY}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/letsencrypt/acme.json"
    networks:
      - proxy-net
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.emby-router.rule=Host(`emby.almonium.com`)"
      - "traefik.http.routers.emby-router.entrypoints=websecure"
      - "traefik.http.routers.emby-router.tls.certresolver=porkbun"
      - "traefik.http.routers.emby-router.service=emby-svc"
      - "traefik.http.services.emby-svc.loadbalancer.server.url=http://host.docker.internal:8096"

  frontend-almonium-com:
    image: nginx:alpine
    container_name: frontend_almonium_com
    volumes:
      - /var/www/almonium-fe:/usr/share/nginx/html:ro
      - ./nginx-configs/spa.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.almonium-com-router.rule=Host(`almonium.com`)"
      - "traefik.http.routers.almonium-com-router.entrypoints=websecure"
      - "traefik.http.routers.almonium-com-router.tls.certresolver=porkbun"
      - "traefik.http.services.almonium-com-svc.loadbalancer.server.port=80"
    restart: unless-stopped

  frontend-almonium-com-staging:
    image: nginx:alpine
    container_name: frontend_almonium_com_staging
    volumes:
      - /var/www/almonium-fe-staging:/usr/share/nginx/html:ro
      - ./nginx-configs/spa.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.almonium-com-staging-router.rule=Host(`staging.almonium.com`)"
      - "traefik.http.routers.almonium-com-staging-router.entrypoints=websecure"
      - "traefik.http.routers.almonium-com-staging-router.tls.certresolver=porkbun"
      - "traefik.http.services.almonium-com-staging-svc.loadbalancer.server.port=80"
    restart: unless-stopped

  frontend-adoptik-com:
    image: nginx:alpine
    container_name: frontend_adoptik_com
    volumes:
      - /var/www/adoptik-fe:/usr/share/nginx/html:ro
    networks:
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adoptik-com-router.rule=Host(`adoptik.almonium.com`)"
      - "traefik.http.routers.adoptik-com-router.entrypoints=websecure"
      - "traefik.http.routers.adoptik-com-router.tls.certresolver=porkbun"
      - "traefik.http.services.adoptik-com-svc.loadbalancer.server.port=80"
    restart: unless-stopped

  static-voices-almonium-com:
    image: nginx:alpine
    container_name: static_voices_almonium_com
    volumes:
      - /home/almonium/voices:/usr/share/nginx/html:ro
    networks:
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.voices-com-router.rule=Host(`voices.almonium.com`)"
      - "traefik.http.routers.voices-com-router.entrypoints=websecure"
      - "traefik.http.routers.voices-com-router.tls.certresolver=porkbun"
      - "traefik.http.services.voices-com-svc.loadbalancer.server.port=80"
    restart: unless-stopped

networks:
  proxy-net:
    external: true
