services:
  traefik:
    image: traefik:v3.4.1
    container_name: traefik_proxy
    command:
      - "--api.insecure=true" # for Traefik dashboard
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.porkbun.acme.email=tech@almonium.com"
      - "--certificatesresolvers.porkbun.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.porkbun.acme.dnschallenge.provider=porkbun"
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080" # Traefik dashboard
    environment:
      - PORKBUN_API_KEY=${SHELL_PORKBUN_API_KEY}
      - PORKBUN_SECRET_API_KEY=${SHELL_PORKBUN_SECRET_KEY}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/letsencrypt/acme.json"
    networks:
      - proxy-net
    restart: unless-stopped

networks:
  proxy-net:
    name: proxy-net
