- name: Ensure host backup dir exists
  file:
    path: /opt/db/backups
    state: directory
    mode: "0755"

# If Postgres container already exists/runs, we do a dump; if first run, this will skip
- name: Check if postgres container exists
  community.docker.docker_container_info:
    name: "postgres_{{ deploy_environment }}"
  register: pg_info
  failed_when: false

- name: Create timestamp fact for backups
  set_fact:
    backup_ts: "{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

- name: Backup databases (skip if container absent)
  shell: |
    set -e
    docker exec {{ 'postgres_' + deploy_environment }} bash -lc '
      set -e
      for DB in almonium almonium_staging; do
        if psql -U {{ db_admin_user | default("postgres") }} -tAc "SELECT 1 FROM pg_database WHERE datname='\''$DB'\''" | grep -q 1; then
          echo "Dumping $DB..."
          pg_dump -U {{ db_admin_user | default("postgres") }} -Fc -d "$DB" > /backups/${DB}_{{ backup_ts }}.dump
          # keep last 7 dumps per DB
          ls -1t /backups/${DB}_*.dump 2>/dev/null | tail -n +8 | xargs -r rm -f
        fi
      done
    '
  when: pg_info is defined and pg_info.containers | length > 0 and pg_info.containers[0].State.Running | default(false)
  args:
    executable: /bin/bash

- name: Ensure db-net exists (internal)
  community.docker.docker_network:
    name: db-net
    internal: true
    state: present

- name: Create DB stack dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /opt/db
    - /opt/db/init

- name: Template DB .env
  template:
    src: env.j2
    dest: /opt/db/.env
    mode: "0600"

- name: Push compose file
  copy:
    src: "{{ playbook_dir }}/../services/postgres/docker-compose.yaml"
    dest: /opt/db/docker-compose.yaml
    mode: "0644"

# Optional: first-time bootstrap (only runs on a fresh data dir)
- name: Template first-run SQL (creates DBs, users, grants)
  template:
    src: 001-bootstrap.sql.j2
    dest: /opt/db/init/001-bootstrap.sql
    mode: "0644"

- name: Up DB stack
  community.docker.docker_compose_v2:
    project_src: /opt/db
    state: present

- name: Wait for Postgres to be ready
  shell: "docker exec {{ 'postgres_' + deploy_environment }} pg_isready -U {{ db_admin_user | default('postgres') }}"
  register: pg_ready
  retries: 30
  delay: 2
  until: pg_ready.rc == 0

# If the volume already existed, ensure DBs/users still exist (idempotent)
- name: Ensure {{ db_name }} database exists
  shell: |
    docker exec {{ 'postgres_' + deploy_environment }} \
      psql -U {{ db_admin_user | default('postgres') }} -tAc \
      "SELECT 1 FROM pg_database WHERE datname='{{ db_name }}'" | grep -q 1 \
      || createdb -U {{ db_admin_user | default('postgres') }} {{ db_name }}
  changed_when: false

- name: Ensure app role exists
  shell: |
    docker exec {{ 'postgres_' + deploy_environment }} \
      psql -U {{ db_admin_user | default('postgres') }} -tAc \
      "SELECT 1 FROM pg_roles WHERE rolname='{{ db_username }}'" | grep -q 1 \
      || psql -U {{ db_admin_user | default('postgres') }} -c \
         "CREATE USER {{ db_username }} WITH PASSWORD '{{ db_password }}';"
  changed_when: false

- name: Grant privileges
  shell: |
    docker exec {{ 'postgres_' + deploy_environment }} \
      psql -U {{ db_admin_user | default('postgres') }} -d {{ db_name }} -c \
      "GRANT ALL PRIVILEGES ON DATABASE {{ db_name }} TO {{ db_username }};
       GRANT USAGE, CREATE ON SCHEMA public TO {{ db_username }};
       ALTER DEFAULT PRIVILEGES IN SCHEMA public
         GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO {{ db_username }};"
  changed_when: false
