db:
  password: ""

jwt:
  secret: ""

stream:
  key: ""
  secret: ""

stripe:
  key: ""
  webhook_secret: ""

rabbitmq:
  password: ""

books:
  db:
    password: ""
  rabbitmq:
    password: ""
  django:
    secret_key: ""
    admin_username: ""
    admin_email: ""
    admin_password: ""
