apple_client_secret: ""
facebook_client_secret: ""
mail_password: ""
openai_key: ""
openai_admin_key: ""
gemini_api_key: ""
rapid_api_key: ""
wordnik_key: ""
yandex_key: ""
zepto_api_key: ""
books:
  publisher_secret: ""
