db_admin_password: ""

postgres_tenant_passwords:
  "almonium:prod": ""
  "almonium:staging": ""
  "fam_sub:prod": ""
  "almonium_books:prod": ""
  "almonium_books:staging": ""

db_backup:
  restic_password: ""
  b2:
    application_key_id: ""
    application_key: ""
