# This playbook contains two plays, executed sequentially.
# Play 1: Fixes the host's DNS configuration.
# Play 2: Deploys the application using the now-corrected host environment.

- name: Play 1 - Fix Host DNS Configuration for Docker
  hosts: "{{ target_host_group }}"
  become: yes # These tasks require root privileges
  gather_facts: no

  tasks:
    - name: Disable systemd-resolved stub listener
      ansible.builtin.lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '^#?DNSStubListener='
        line: 'DNSStubListener=no'
        state: present
      notify: Restart systemd-resolved

    - name: Check if /etc/resolv.conf is a symlink
      ansible.builtin.stat:
        path: /etc/resolv.conf
      register: resolv_conf_stat

    - name: Remove symlinked /etc/resolv.conf
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: absent
      when: resolv_conf_stat.stat.islnk is defined and resolv_conf_stat.stat.islnk

    - name: Create a static /etc/resolv.conf for the host
      ansible.builtin.copy:
        dest: /etc/resolv.conf
        content: |
          # Generated by Ansible to fix Docker DNS
          nameserver 8.8.8.8
          nameserver 1.1.1.1
        mode: '0644'
      # We don't notify here to avoid a double restart. Flushing handlers is enough.

    # Handlers will run at the end of the play. We flush them here to ensure
    # resolved is restarted before we try to restart docker.
    - name: Flush handlers to apply systemd-resolved changes
      ansible.builtin.meta: flush_handlers

    - name: Ensure Docker daemon is restarted to pick up new DNS config
      ansible.builtin.service:
        name: docker
        state: restarted

  handlers:
    - name: Restart systemd-resolved
      ansible.builtin.service:
        name: systemd-resolved
        state: restarted

# --- The second play begins here ---

- name: Play 2 - Deploy Almonium BE Application (Blue/Green)
  hosts: "{{ target_host_group }}"
  gather_facts: false
  vars:
    # All --extra-vars from GitHub Actions are available here
    infra_root: "/home/almonium/infra"
    project_name_base: "almonium-be"
    APP_INTERNAL_PORT: "9998"

  tasks:
    - name: Determine project name suffix and color file path
      ansible.builtin.set_fact:
        project_name_suffix: "_{{ DEPLOY_ENVIRONMENT }}"
        color_file_path: "{{ infra_root }}/.next_color_{{ DEPLOY_ENVIRONMENT }}"

    - name: Read current color for the environment
      ansible.builtin.slurp:
        src: "{{ color_file_path }}"
      register: color_file_content
      failed_when: false

    - name: Determine initial color based on file content
      ansible.builtin.set_fact:
        _color_from_file: >-
          {{ color_file_content.content | b64decode
             if color_file_content.content is defined and color_file_content.content != ""
             else 'blue' }}

    - name: Set target DEPLOY_SLOT
      ansible.builtin.set_fact:
        DEPLOY_SLOT: "{{ 'green' if _color_from_file == 'green' else 'blue' }}"

    - name: Set PREVIOUS_SLOT based on determined DEPLOY_SLOT
      ansible.builtin.set_fact:
        PREVIOUS_SLOT: "{{ 'green' if DEPLOY_SLOT == 'blue' else 'blue' }}"

    - name: Set local healthcheck port for target DEPLOY_SLOT
      ansible.builtin.set_fact:
        LOCAL_HEALTHCHECK_PORT: >-
          {%- if DEPLOY_ENVIRONMENT == 'staging' -%}
            {{- '9978' if DEPLOY_SLOT == 'blue' else '9979' -}}
          {%- else -%}
            {{- '9988' if DEPLOY_SLOT == 'blue' else '9989' -}}
          {%- endif -%}

    - name: Set Docker Compose project name base for environment
      ansible.builtin.set_fact:
        DOCKER_COMPOSE_PROJECT_NAME: "{{ project_name_base }}{{ project_name_suffix }}"

    - name: Log in to GitHub Container Registry (GHCR)
      community.docker.docker_login:
        registry: ghcr.io
        username: "{{ DEPLOY_GH_ACTOR }}"
        password: "{{ DEPLOY_GH_TOKEN }}"

    - name: "Deploy TARGET slot: {{ DEPLOY_SLOT }}"
      ansible.builtin.import_role:
        name: deploy_app_slot

    - name: "Stop and remove PREVIOUS slot: {{ PREVIOUS_SLOT }}"
      ansible.builtin.command: >-
        docker stop app_{{ DEPLOY_ENVIRONMENT }}_{{ PREVIOUS_SLOT }} &&
        docker rm app_{{ DEPLOY_ENVIRONMENT }}_{{ PREVIOUS_SLOT }}
      register: stop_previous_result
      changed_when: "'Error: No such container' not in stop_previous_result.stderr | default('') and stop_previous_result.rc == 0"
      failed_when: false
      when: PREVIOUS_SLOT is defined and PREVIOUS_SLOT != '' and PREVIOUS_SLOT != DEPLOY_SLOT

    - name: "Update color file to point to next slot"
      ansible.builtin.copy:
        content: "{{ 'green' if DEPLOY_SLOT == 'blue' else 'blue' }}"
        dest: "{{ color_file_path }}"
        mode: '0644'
      become: yes # Assuming this needs root, as infra_root is likely root-owned

    - name: "Deployment Summary"
      ansible.builtin.debug:
        msg: "✅ Deploy for ENV: [{{ DEPLOY_ENVIRONMENT }}], successfully switched to SLOT: [{{ DEPLOY_SLOT }}] for HOSTNAME: [{{ API_HOSTNAME }}]"
