- name: Deploy TG voices
  hosts: almonium

  tasks:
    - name: Update infra repository
      ansible.builtin.git:
        repo: https://github.com/almonium-platform/almonium-infra.git
        dest: /home/almonium/infra
        version: main
        force: true

    - name: Deploy TG voices
      community.docker.docker_compose_v2:
        project_src: /home/almonium/infra/services/tg-voices
        state: present
        pull: always
        remove_orphans: true
