services:
  almonium-fe-prod:
    image: ghcr.io/almonium-platform/almonium-fe:${ALMONIUM_FE_PROD_IMAGE_TAG:-latest}
    container_name: almonium_fe_prod
    volumes:
      - ../../nginx-configs/spa.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.almonium-prod-router.rule=Host(`almonium.com`)"
      - "traefik.http.routers.almonium-prod-router.entrypoints=websecure"
      - "traefik.http.routers.almonium-prod-router.tls.certresolver=porkbun"
      - "traefik.http.services.almonium-prod-svc.loadbalancer.server.port=80"
    restart: unless-stopped

  almonium-fe-staging:
    image: ghcr.io/almonium-platform/almonium-fe:${ALMONIUM_FE_STAGING_IMAGE_TAG:-latest}
    container_name: almonium_fe_staging
    volumes:
      - ../../nginx-configs/spa.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.almonium-staging-router.rule=Host(`staging.almonium.com`)"
      - "traefik.http.routers.almonium-staging-router.entrypoints=websecure"
      - "traefik.http.routers.almonium-staging-router.tls.certresolver=porkbun"
      - "traefik.http.services.almonium-staging-svc.loadbalancer.server.port=80"
    restart: unless-stopped

networks:
  proxy-net:
    external: true
