name: Sync Ansible Configs to Server

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'ansible/**'

jobs:
  sync-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and pull Ansible changes
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.CLOUD_HOST }}
          username: ${{ secrets.CLOUD_USERNAME }}
          key: ${{ secrets.CLOUD_KEY }}
          script: |
            echo "--- Navigating to infra repository ---"
            cd /home/almonium/infra
            
            echo "--- Pulling latest changes from master to update Ansible configs ---"
            git pull origin master
            
            echo "--- Ansible sync complete ---"
