name: Sync Ansible Configs to Server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync-ansible:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v5
        with:
          playbook: playbook-sync-infra.yaml
          directory: ansible
          key: ${{ secrets.CLOUD_KEY }}
          options: |
            -i inventory/hosts.ini
            --limit almonium
