name: Deploy Traefik Proxy
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'traefik/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout infra code
        uses: actions/checkout@v4

      - name: Deploy Traefik to Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.CLOUD_HOST }}
          username: ${{ secrets.CLOUD_USERNAME }}
          key: ${{ secrets.CLOUD_KEY }}
          envs: |
            VAR_PORKBUN_API_KEY=${{ secrets.PORKBUN_API_KEY }}
            VAR_PORKBUN_SECRET_KEY=${{ secrets.PORKBUN_SECRET_KEY }}
          script: |
            echo "Deploying Traefik..."
            cd /home/almonium/infra/traefik # Or where you cloned almonium-infra/traefik

            # Make Porkbun API keys available to docker-compose
            # The docker-compose.yaml above refers to these exact names
            export PORKBUN_API_KEY="${VAR_PORKBUN_API_KEY}"
            export PORKBUN_SECRET_KEY="${VAR_PORKBUN_SECRET_KEY}"

            # Create acme.json with correct permissions if it doesn't exist
            if [ ! -f "./acme.json" ]; then
              touch ./acme.json
              chmod 600 ./acme.json
            fi

            docker compose pull traefik # Pull the specified image version
            docker compose up -d --remove-orphans
            echo "Traefik deployment attempted."
