name: Deploy Traefik Proxy

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'traefik/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Traefik
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.CLOUD_HOST }}
          username: ${{ secrets.CLOUD_USERNAME }}
          key: ${{ secrets.CLOUD_KEY }}
          script: |
            echo "--- Navigating to infra repository ---"
            cd /home/almonium/infra
            
            echo "--- Pulling latest changes from master ---"
            git pull origin master
            
            echo "--- Navigating to Traefik directory ---"
            cd /home/almonium/infra/traefik
            
            echo "--- Exporting secrets for Docker Compose ---"
            export SHELL_PORKBUN_API_KEY="${{ secrets.PORKBUN_API_KEY }}"
            export SHELL_PORKBUN_SECRET_KEY="${{ secrets.PORKBUN_SECRET_KEY }}"

            # Create acme.json with correct permissions if it doesn't exist
            if [ ! -f "./acme.json" ]; then
              touch ./acme.json
              chmod 600 ./acme.json
            fi

            echo "--- Pulling latest Traefik image ---"
            docker compose pull

            echo "--- Deploying Traefik stack ---"
            docker compose up -d --remove-orphans
            
            echo "--- Traefik deployment complete ---"
