name: Deploy Postgres DB

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'ansible/**'
      - 'services/postgres/**'
      - '.github/workflows/deploy-db.yaml'

jobs:
  deploy-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v5

      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v4
        with:
          playbook: playbook-deploy-db.yaml
          directory: ansible
          key: ${{ secrets.CLOUD_KEY }}
          vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD_DB }}
          options: |
            -i inventory/hosts.ini
            --limit almonium
            -e ansible_python_interpreter=/usr/bin/python3
