name: Deploy TG Voices

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'services/tg-voices/**'
      - '.github/workflows/deploy-tg-voices.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v5
        with:
          playbook: playbook-deploy-tg-voices.yaml
          directory: ansible
          key: ${{ secrets.CLOUD_KEY }}
          options: |
            -i inventory/hosts.ini
            --limit almonium
