name: Deploy Almonium FE

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'services/almonium-fe/**'
      - '.github/workflows/deploy-almonium-fe.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Almonium FE
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.CLOUD_HOST }}
          username: ${{ secrets.CLOUD_USERNAME }}
          key: ${{ secrets.CLOUD_KEY }}
          script: |
            set -euo pipefail

            cd /home/almonium/infra
            git fetch origin main
            git reset --hard origin/main
            
            cd /home/almonium/infra/almonium-fe

            docker compose pull
            docker compose up -d --remove-orphans
