name: Deploy RabbitMQ Service

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'ansible/**'
      - '.github/workflows/deploy-rabbitmq.yaml'

jobs:
  deploy_rabbitmq:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v5

      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: playbook-deploy-rabbitmq.yaml
          directory: ansible
          key: ${{ secrets.CLOUD_KEY }}
          vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD_RABBITMQ }}
          options: |
            -i inventory/hosts.ini
            --limit almonium
            -e ansible_python_interpreter=/usr/bin/python3
            --vault-id rabbitmq@${{ secrets.ANSIBLE_VAULT_PASSWORD_RABBITMQ }}
            --vault-id almonium_prod@${{ secrets.ANSIBLE_VAULT_PASSWORD_ALMONIUM_PROD }}
            --vault-id almonium_staging@${{ secrets.ANSIBLE_VAULT_PASSWORD_ALMONIUM_STAGING }}
