name: Deploy RabbitMQ Service

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'ansible/**'
      - '.github/workflows/deploy-rabbitmq.yaml'

jobs:
  deploy_rabbitmq:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v5

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.CLOUD_KEY }}

      - name: Install Ansible and Docker collection
        run: |
          set -euo pipefail
          python -m venv ansible_venv
          source ansible_venv/bin/activate
          pip install ansible
          ansible-galaxy collection install community.docker

      - name: Deploy RabbitMQ with Ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          VAULT_PASS_ALMONIUM_PROD: ${{ secrets.ANSIBLE_VAULT_PASSWORD_ALMONIUM_PROD }}
          VAULT_PASS_ALMONIUM_STAGING: ${{ secrets.ANSIBLE_VAULT_PASSWORD_ALMONIUM_STAGING }}
        run: |
          set -euo pipefail

          source ansible_venv/bin/activate
          cd ansible

          mkdir -p ~/.ansible
          umask 077

          VAULT_ALMONIUM_PROD="$(mktemp ~/.ansible/vault-pass-almonium-prod.XXXXXX)"
          VAULT_ALMONIUM_STAGING="$(mktemp ~/.ansible/vault-pass-almonium-staging.XXXXXX)"

          trap 'rm -f "$VAULT_ALMONIUM_PROD" "$VAULT_ALMONIUM_STAGING"' EXIT

          printf "%s" "$VAULT_PASS_ALMONIUM_PROD" > "$VAULT_ALMONIUM_PROD"
          printf "%s" "$VAULT_PASS_ALMONIUM_STAGING" > "$VAULT_ALMONIUM_STAGING"

          ansible-playbook \
            -i inventory/hosts.ini \
            --limit almonium \
            playbook-deploy-rabbitmq.yaml \
            -e ansible_python_interpreter=/usr/bin/python3 \
            --vault-id almonium_prod@"$VAULT_ALMONIUM_PROD" \
            --vault-id almonium_staging@"$VAULT_ALMONIUM_STAGING"
