name: Deploy Postgres DB

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'ansible/playbook-deploy-db.yaml'
      - 'ansible/roles/deploy_db_stack/**'
      - 'ansible/vars/stacks/db/**'
      - 'services/postgres/**'
      - '.github/workflows/deploy-db.yaml'

jobs:
  deploy-db:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout infra repo
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@3363d6aa333ecb41ef01579bc5eb4412b3d6802f # v5
        with:
          playbook: playbook-deploy-db.yaml
          directory: ansible
          key: ${{ secrets.CLOUD_KEY }}
          known_hosts: ${{ secrets.CLOUD_KNOWN_HOSTS }}
          vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD_DB }}
          options: |
            -i inventory/hosts.ini
            --limit almonium
            -e ansible_python_interpreter=/usr/bin/python3
